# Generated by Django 3.2.25 on 2024-03-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='category',
        ),
        migrations.AddField(
            model_name='good',
            name='categories',
            field=models.ManyToManyField(to='goods.Category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='good',
            name='product_type',
            field=models.CharField(choices=[('BOOK', 'Книга'), ('MOVIE', 'Фильм'), ('MUSIC', 'Музыка'), ('PICTURE', 'Картина')], max_length=100, verbose_name='Тип продукта'),
        ),
    ]
