# Generated by Django 3.2.25 on 2024-04-02 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0003_auto_20240314_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='users.user', verbose_name='Создатель'),
            preserve_default=False,
        ),
    ]
